#!/bin/sh /etc/rc.common

START=99
STOP=15

start() {
    /usr/bin/led_signal.lua &
    echo $! > /var/run/dioled.pid
}

stop() {
    kill -9 $(cat /var/run/dioled.pid) 2>/dev/null
    rm -f /var/run/dioled.pid
}
