#!/bin/sh /etc/rc.common

START=95
STOP=10

start() {
  logger "Starting dioled service"
  /usr/bin/lua /usr/bin/led_signal.lua &
}

stop() {
  logger "Stopping dioled service"
  killall led_signal.lua 2>/dev/null
}
